# Generated by Django 4.2.3 on 2023-08-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='image_file',
            new_name='image_path',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_file',
            new_name='video_path',
        ),
    ]
