# Generated by Django 4.2.3 on 2023-08-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_rename_image_file_video_image_path_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='video',
            table='videos',
        ),
    ]
